version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - ebios-network
    environment:
      - REACT_APP_API_URL=http://localhost:3000

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ebios
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - FRONTEND_URL=http://localhost:80
    depends_on:
      - db
    networks:
      - ebios-network
    volumes:
      - ./api:/app
      - /app/node_modules

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ebios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - ebios-network

volumes:
  postgres_data:

networks:
  ebios-network:
    driver: bridge