apiVersion: v1
kind: Service
metadata:
  name: ebios-webapp
  namespace: ebios
spec:
  selector:
    app: ebios-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer