apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebios-webapp
  namespace: ebios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebios-webapp
  template:
    metadata:
      labels:
        app: ebios-webapp
    spec:
      containers:
      - name: ebios-webapp
        image: ebios-webapp:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5